  - name: install httpd package
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
    #tags: install_apache

  - name: start httpd service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"
    tags: start_apache

  - name: change email address for admin
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin root@localhost.gmail
    when: ansible_distribution == "CentOS"
    tags: lineinfile_httpd
    register: httpd # this is output var only for this change!!!!

  - name: restart httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed
    tags: httpd_restart

  - name: install apache2 package
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    tags: install_apache

  - name: start apache2
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"
    tags: start_apache

  - name: copy a file
    copy:
      src: default_html.html
      dest: /var/www/html/index.html
      mode: 0644
      owner: demousr
      group: root
    tags: index_html
