---

- hosts: all
  become: true
  tasks:
  - name: install httpd package
    yum:
      name: 
        - httpd
        - php  
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
    #tags: install_apache

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"
    tags: start_apache

  - name: install apache2 package
    apt:
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    tags: install_apache

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"
    tags: start_apache

  - name: copy a file
    copy:
      src: default_html.html
      dest: /var/www/html/index.html
      mode: 0644
      owner: demousr
      group: root
    tags: index_html

- hosts: all
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform 
    unarchive: 
      src: https://releases.hashicorp.com/terraform/1.3.2/terraform_1.3.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: demousr
      group: root


- hosts: centos_srv
  become: true
  tasks: 
  - name: Install mariadb on centos
    yum: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

    # - name: start mariadb
    #systemd:
    #name: mariadb
    # state: restarted
    #when: ansible_distribution == "CentOS"
    #tags: start_mariadb


