- hosts: all
  become: true
  pre_tasks:

  - name: install_updates CentOS
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"
    tags: always

  - name: install_updates Ubuntu
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    tags: always

